name: Full Compile Check

on: [workflow_dispatch]

jobs:
  full-compile-check:
    name: ${{ matrix.platform.name }}
    runs-on: ${{ matrix.platform.os }}
    timeout-minutes: 20

    strategy:
      fail-fast: false
      matrix:
        platform:
          - { name: Linux/GCC, os: ubuntu-latest, extraflags: "--system-sdl" }
          - { name: Linux/Clang, os: ubuntu-latest, extraflags: "--system-sdl", prefix: "CC=clang CXX=clang++"}
          - { name: Windows/VS2022, os: windows-2022, extraflags: "-G 'Visual Studio 17 2022'" }
          - { name: Mac, os: macos-latest }

    steps:
      - name: Install Linux build dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install libsdl3-dev

      - uses: actions/checkout@v4
        with: {submodules: 'recursive'}

      - name: Install GNS via vcpkg
        shell: bash
        run: |
          if [ "$RUNNER_OS" == "Windows" ]; then
            vcpkg install gamenetworkingsockets:x64-windows
          else
            vcpkg install gamenetworkingsockets
          fi
          echo "CMAKE_TOOLCHAIN_FILE=$VCPKG_INSTALLATION_ROOT/scripts/buildsystems/vcpkg.cmake" >> $GITHUB_ENV

      - run: ${{matrix.platform.prefix}} python3 build.py --dependencies --configure --build ${{matrix.platform.extraflags}}
